FROM rasa/rasa-sdk:2.6.0

USER root

WORKDIR/app

COPY requirements.txt /app

COPY actions.py /app

COPY FOM.csv/app

COPY  departments.csv/app

COPY multiple_utterance.csv/app

COPY special_item_list.csv/app

RUN pip3 install -r requirements.txt

CMD[“start”, “—-actions”, “actions”]

USER 1001
